app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: 基础文本摘要器
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: marketplace
  value:
    marketplace_plugin_unique_identifier: langgenius/siliconflow:0.0.33@6792acf632f24f1c41a3192a78ef181f7149811a8dfd9a16ade984978613f79c
    version: null
kind: app
version: 0.4.0
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: start
        targetType: llm
      id: 1761912319586-source-1761912379573-target
      source: '1761912319586'
      sourceHandle: source
      target: '1761912379573'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: llm
        targetType: end
      id: 1761912379573-source-1761983604956-target
      source: '1761912379573'
      sourceHandle: source
      target: '1761983604956'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        selected: false
        title: 开始
        type: start
        variables:
        - default: ''
          hint: ''
          label: text
          max_length: 2000
          options: []
          placeholder: ''
          required: true
          type: paragraph
          variable: text
      height: 88
      id: '1761912319586'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 242
    - data:
        context:
          enabled: true
          variable_selector:
          - '1761912319586'
          - text
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: deepseek-ai/DeepSeek-R1
          provider: langgenius/siliconflow/siliconflow
        prompt_template:
        - id: 3ec9109a-6979-46de-856f-f517542d43da
          role: system
          text: 请对以下文本进行精炼的中文摘要：{{#1761912319586.text#}}
        selected: false
        title: LLM
        type: llm
        vision:
          enabled: false
      height: 88
      id: '1761912379573'
      position:
        x: 382
        y: 282
      positionAbsolute:
        x: 382
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 242
    - data:
        outputs:
        - value_selector:
          - '1761912379573'
          - text
          value_type: string
          variable: summary
        selected: false
        title: 结束
        type: end
      height: 88
      id: '1761983604956'
      position:
        x: 684
        y: 282
      positionAbsolute:
        x: 684
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 242
    viewport:
      x: 70.73251742059392
      y: -17.243791553636044
      zoom: 1.0410215976841128
  rag_pipeline_variables: []
